### ISSUE TITLE
Incompatability with Snow! Real Magic

### ISSUE THREAD

**Issue by danaYatsuta** [Reforged-Hub/radium-upstream#37] opened 2024-09-08 12:49 UTC
### Version

Minecraft 1.20.1
NeoForge 47.1.106
Radium 0.12.3+git.50c5c33
Snow! Real Magic 10.5.1

### Reproduction Steps

Launch the game with Radium, Snow! Real Magic and Kiwi (required library for Snow! Real Magic). Reproducible with just these three mods without any others installed.

### Crash Report File

[https://mclo.gs/YF86CVc](https://mclo.gs/YF86CVc)

**Comment by dima-dencep** [comment] 2024-09-08 14:23
Duplicate of #34

**Closed as completed by dima-dencep** 2024-09-08 14:23 UTC
Labels: duplicate
